backstage:
  serviceAccount:
    create: true
    name: backstage

  backstage:
    image:
      repository: ghcr.io/my-silly-organisation/backstage
      tag: 1.31.2

    extraEnvVars:
    - name: NODE_ENV
      value: development
    - name: GITHUB_TOKEN
      value: "change me"
    - name: ARGOCD_URL
      value: "http://my-argo-cd-argocd-server.argocd.svc/api/v1/"
    - name: ARGOCD_AUTH_TOKEN
      value: "argocd.token=changeme"
    - name: BASE_URL
      value: "backstage.localhost"
    - name: CATALOG_LOCATION
      value: "https://raw.githubusercontent.com/dirien/backstage-demo/main/catalog-info.yaml"

    appConfig:
      app:
        baseUrl: http://${BASE_URL}:7007

      backend: # Note that the baseUrl should be the URL that the browser and other clients
        # should use when communicating with the backend, i.e. it needs to be
        # reachable not just from within the backend host, but from all of your
        # callers. When its value is "http://localhost:7007", it's strictly private
        # and can't be reached by others.
        baseUrl: http://${BASE_URL}:7007
        # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
        # all interfaces, the most permissive setting. The right value depends on your specific deployment.
        listen:
          port: 7007

        csp:
          connect-src: ["'self'", 'http:', 'https:']
          # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
          # Default Helmet Content-Security-Policy values can be removed by setting the key to false
        reading:
          allow:
          - host: github.com
          - host: api.github.com
          - host: raw.githubusercontent.com
        cors:
          origin: http://${BASE_URL}
          methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
          credentials: true
          Access-Control-Allow-Origin: '*'
        database:
          client: pg
          connection:
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
      integrations:
        github:
        - host: github.com
          # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
          # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
          token: ${GITHUB_TOKEN}
        ### Example for how to add your GitHub Enterprise instance using the API:
        # - host: ghe.example.net
        #   apiBaseUrl: https://ghe.example.net/api/v3
        #   token: ${GHE_TOKEN}

      proxy: ### Example for how to add a proxy endpoint for the frontend.
        ### A typical reason to do this is to handle HTTPS and CORS for internal services.
        # '/test':
        #   target: 'https://example.com'
        #   changeOrigin: true
        '/argocd/api':
          target: ${ARGOCD_URL}
          changeOrigin: true
          # only if your argocd api has self-signed cert
          secure: false
          headers:
            Cookie: ${ARGOCD_AUTH_TOKEN}
      techdocs:
        builder: 'local' # Alternatives - 'external'
        generator:
          runIn: 'docker' # Alternatives - 'local'
        publisher:
          type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

      auth: # see https://backstage.io/docs/auth/ to learn about auth providers
        environment: development
        providers: # See https://backstage.io/docs/auth/guest/provider
          guest: {}

      scaffolder:
      # see https://backstage.io/docs/features/software-templates/configuration for software template options

      catalog: # Overrides the default list locations from app-config.yaml as these contain example data.
      # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
      # on how to get entities into the catalog.
        locations:
        - type: url
          target: ${CATALOG_LOCATION}
          rules:
          - allow:  [User,Domain, Systems, Group, Component, System, API, Resource, Location, Template]

      kubernetes:
        serviceLocatorMethod:
          type: 'multiTenant'
        clusterLocatorMethods:
        - type: 'config'
          clusters:
          - url: kubernetes.default.svc.cluster.local:443
            name: local
            authProvider: 'serviceAccount'
            skipTLSVerify: false
            skipMetricsLookup: true
      # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

      # see https://backstage.io/docs/permissions/getting-started for more on the permission framework
      permission: # setting this to `false` will disable permissions
        enabled: true

  ingress:
    enabled: true
    className: nginx
    host: "backstage.localhost"
